configuration:
  dependencies:
  - "mvn://org.codehaus.groovy:groovy-all:pom:2.5.2"
  - "mvn://org.apache.ivy:ivy:2.4.0"
flows:
  default:
  - script: test.groovy
  onPush:
  - log: "${event.sender} pushed ${event.commitId} to ${event.payload.repository.full_name}"
triggers:
- github:
    useInitiator: true
    entryPoint: onPush
    conditions:
      type: push
