configuration:
  dependencies:
  - "mvn://org.codehaus.groovy:groovy-all:pom:2.5.2"
  - "mvn://org.apache.ivy:ivy:2.4.0"
  arguments:
    user: ${crypto.decryptString("y5ox+BFRAX5ftXLpjEeUMA==")}
flows:
  default:
  - script: ./scripts/test.groovy
  onPush:
  - log: "${event.sender} - ${event.commitId} to ${event.payload.repository.full_name}"
  - log: "Username - ${user}"
  - script: ./scripts/test.groovy
triggers:
- github:
    entryPoint: "onPush"
    conditions:
      type: "push"
